### ISSUE TITLE
This Github.io Page needs a ReadMe--what goes in it?

### ISSUE THREAD

**Issue by lianplass** [APA-Technology-Division/APA-Technology-Division.github.io#13]
**Is your feature request related to a problem? Please describe.**
I would like to link directly to the Pages repository on Pages navbars, but I just can't justify that without a proper ReadMe.  What information should be included on it to make it worth the visit?

If this is well put together, we can redirect the index.html file to the GitHub ReadMe (saves time on building a landing page that serves the same purpose)

**Describe the solution you'd like**
I need recommendations for the APA-Technology-Division.github.io ReadMe Page.

**Additional context**
images, screenshots, GIFs, text formatting?

**Current Proposed Outline:**
[PAGES BANNER IMAGE]
* Repo description - in a few sentences, how would you describe the technology division's GitHub pages site?  How can we make sure it is distinct from our APA domain site?

* Site Map
- Act Like a Planner - description and screen capture + contribution button
- Other Items - (e.g., urban-and-regional-planning-resources repo) descriptions and screen captures
- Hackathons - description and screen capture

**Comment by d-wasserman** [comment]
I would just suggest a simple site map. I think we should think about a folder structure for pages down the line, but then we have to worry about redirects. 

A simple map is fine.

**Comment by lianplass** [comment]
Good enough for now (see latest Commit flagging this issue).  May reopen later if additional pages are added.

**Comment by d-wasserman** [comment]
Is it possible to add it this link here: APA-Technology-Division.github.io
