### ISSUE TITLE
Link Handling for New ChatGPT

### ISSUE THREAD

**Issue by lianplass** [APA-Technology-Division/APA-Technology-Division.github.io#14]
**Is your feature request related to a problem? Please describe.**
ChatGPT now allows you to share links to prompt outputs.  DB submissions now contain links to sample outputs, but a new JS function needs to be implemented to handle those links.

**Describe the solution you'd like**
Add a new JS function to show links as more than just plain text.

**Comment by d-wasserman** [comment]
I can see how that is problematic. It might just be HTML if you can add the link tags for that particular area.

**Comment by lianplass** [comment]
Fixed with the latest commit.  Try searching "guidelines" to see new result!
